- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPe+ML1sKaVXa3LnlkmHxEDh0R2myigY9jRaqr3bz/jN ansible"

- name: generste sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}" 
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0664
  notify: restart_sshd
